name: Update Specific Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Update branches
      run: |
        # List of branches to update
        branches=("TL" "Pierre" "Emile" "Yanis")

        # Fetch all branches
        git fetch --all

        # Loop through each branch and attempt to update
        for branch in "${branches[@]}"; do
          git checkout $branch
          git merge origin/main || echo "Merge conflict in $branch"
          git push origin $branch || echo "Failed to push $branch"
        done
