name: Merge main into all branches

on:
  push:
    branches:
      - main

jobs:
  merge-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get all remote branches
        run: |
          git fetch origin
          for branch in $(git branch -r | grep -v 'main' | sed 's/origin\///'); do
            echo "Merging into $branch..."
            git checkout $branch
            git merge origin/main --no-edit || echo "Merge conflict in $branch, skipping..."
            git push origin $branch || echo "Push failed for $branch"
          done
